name: edcurve

networks:
  NETWORK:
    external: true

services:
  user_service:
    build: ./
    restart: always
    networks:
      - NETWORK
    volumes:
      - /edcurve/webconf/:/edcurve/webconf/
    logging:
        options:
            max-size: '10m'
            max-file: '3'
        driver: json-file
