"""Added table relation

Revision ID: 98cd58c3a2cd
Revises: 9ebadfc2a6db
Create Date: 2026-07-22 20:04:41.337425

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "98cd58c3a2cd"
down_revision: str | Sequence[str] | None = "9ebadfc2a6db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_relation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_user_id", sa.Integer(), nullable=False),
        sa.Column("to_user_id", sa.Integer(), nullable=False),
        sa.Column("relation_type", sa.Enum("tutor_of", "parent_of", name="relation_type"), nullable=False),
        sa.Column("subjects", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("level", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "paused", "archived", name="relation_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("parent_rights", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("from_user_id <> to_user_id", name="ck_relation_no_self"),
        sa.ForeignKeyConstraint(["from_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_relation_from_type", "user_relation", ["from_user_id", "relation_type"], unique=False)
    op.create_index("ix_relation_to", "user_relation", ["to_user_id"], unique=False)
    op.create_index(op.f("ix_user_relation_from_user_id"), "user_relation", ["from_user_id"], unique=False)
    op.create_index(op.f("ix_user_relation_status"), "user_relation", ["status"], unique=False)
    op.create_index(op.f("ix_user_relation_to_user_id"), "user_relation", ["to_user_id"], unique=False)
    op.create_index(
        "uq_active_relation",
        "user_relation",
        ["from_user_id", "to_user_id", "relation_type"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_active_relation", table_name="user_relation", postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f("ix_user_relation_to_user_id"), table_name="user_relation")
    op.drop_index(op.f("ix_user_relation_status"), table_name="user_relation")
    op.drop_index(op.f("ix_user_relation_from_user_id"), table_name="user_relation")
    op.drop_index("ix_relation_to", table_name="user_relation")
    op.drop_index("ix_relation_from_type", table_name="user_relation")
    op.drop_table("user_relation")
    # ### end Alembic commands ###
