"""created user table

Revision ID: 9ebadfc2a6db
Revises:
Create Date: 2026-07-20 22:12:42.312402

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ebadfc2a6db"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "basic_role", sa.Enum("tutor", "student", name="basic_role"), server_default="student", nullable=False
        ),
        sa.Column(
            "account_status",
            sa.Enum("managed", "invited", "active", "blocked", "deleted", name="account_status"),
            server_default="managed",
            nullable=False,
        ),
        sa.Column("email", sa.String(length=512), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("nickname", sa.String(length=200), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("contacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("messengers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("locale", sa.String(length=16), server_default="ru", nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("consent", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_account_status"), "user", ["account_status"], unique=False)
    op.create_index(op.f("ix_user_user_id"), "user", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_account_status"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
